services:
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  team_security:
    build: ./consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "consumer.py", "--queue_name", "security", "--channels", "3", "--exchange", "high", "--queue_bindings", "[{\"priority\": \"high\", \"routing_key\": \"accident.security\"},{\"priority\": \"high\", \"routing_key\": \"brawl.security\"},{\"priority\": \"high\", \"routing_key\": \"not_on_list.security\"}]"]
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=5'

  team_cleanup:
    build: ./consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "consumer.py", "--queue_name", "cleanup", "--channels", "3", "--exchange", "high", "--queue_bindings", "[{\"priority\": \"high\", \"routing_key\": \"dirty_table.cleanup\"},{\"priority\": \"high\", \"routing_key\": \"broken_items.cleanup\"},{\"priority\": \"high\", \"routing_key\": \"dirty_floor.cleanup\"}]"]
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=5'